Ce que tu dois faire : Ajoute des cellules Markdown entre chaque étape importante. Exemple :

Avant le nettoyage → explique les problèmes trouvés
Après chaque transformation → explique ta décision
À la fin → écris un résumé des insights

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('customershoppingbehavior.csv')

In [3]:
data.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:
data.shape

(3900, 18)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [6]:
data.describe(include="all")

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [7]:
data.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [8]:
# we habe 37 null value in rating so we need to replace this by median or mean so we will use median because not change with outliers values
data['Review Rating'] = data.groupby('Category')['Review Rating'].transform(lambda x : x.fillna(x.median()))

In [9]:
data.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [10]:
# Renaming columns according to snake casing for better readability and documentation

data.columns = data.columns.str.lower()
data.columns = data.columns.str.replace(' ','_')
data = data.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [11]:
data.head(2)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly

This is formatted as code

In [12]:
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
data['age_group'] = pd.qcut(data['age'], q=4, labels = labels)

In [13]:
data[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [14]:
data['frequency_of_purchases'].unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [15]:
data['frequency_of_purchases'].value_counts()

frequency_of_purchases
Every 3 Months    584
Annually          572
Quarterly         563
Monthly           553
Bi-Weekly         547
Fortnightly       542
Weekly            539
Name: count, dtype: int64

Annually → 365 jours
Quarterly → 90 jours (≈ 3 mois)
Monthly → 30 jours
Weekly → 7 jours
Bi-Weekly → 14 jours
Fortnightly → 14 jours
Every 3 Months → 90 jours

In [16]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

In [17]:
data['purchases frequency days'] = data['frequency_of_purchases'].map(frequency_mapping)

In [18]:
data[['frequency_of_purchases','purchases frequency days']].head(10)

  frequency_of_purchases  purchases frequency days
0            Fortnightly                        14
1            Fortnightly                        14
2                 Weekly                         7
3                 Weekly                         7
4               Annually                       365
5                 Weekly                         7
6              Quarterly                        90
7                 Weekly                         7
8               Annually                       365
9              Quarterly                        90

we have two columns are similar so we need to keep just one and delete other one

In [19]:
data.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group,purchases frequency days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,Middle-aged,365

In [20]:
(data['discount_applied'] == data['promo_code_used']).all()

np.True_

In [21]:
# so they are similar
data = data.drop('promo_code_used',axis =1)

In [22]:
data.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchases frequency days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365

In [23]:
!pip install pyodbc sqlalchemy

Requirement already satisfied: pyodbc in c:\users\admin\anaconda3\lib\site-packages (5.3.0)
Requirement already satisfied: sqlalchemy in c:\users\admin\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\admin\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\admin\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

* SQLAlchemy est une bibliothèque Python qui permet de parler avec des bases de données.
* create_engine est la fonction qui crée le pont entre Python et SQL Server :

Python (pandas)  ←→  **create_engine**   ←→  SQL Server

urllibEncoder les caractères spéciaux dans la connexion

In [24]:
import pyodbc
print(pyodbc.drivers())

['SQL Server', 'SQL Server Native Client RDA 11.0', 'ODBC Driver 17 for SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [25]:
from sqlalchemy import create_engine
import urllib
import pandas as pd

# Connexion
params = urllib.parse.quote_plus(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=CROWN\\SQLEXPRESS;"
    "DATABASE=customer_behavior_bdd;"
    "UID=sa;"
    "PWD=F135335878;"
    "TrustServerCertificate=yes;"
)

engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

In [26]:

# ETAPE 1 — Écrire les données dans SQL Server
data.to_sql("customer", engine, if_exists="replace", index=False)
print("✅ Table créée avec succès !")

✅ Table créée avec succès !

In [27]:
# ETAPE 2 — Lire les données
df_result = pd.read_sql("SELECT  * FROM customer;", engine)
print(df_result)

      customer_id  age  gender item_purchased     category  purchase_amount  \
0               1   55    Male         Blouse     Clothing               53
1               2   19    Male        Sweater     Clothing               64
2               3   50    Male          Jeans     Clothing               73
3               4   21    Male        Sandals     Footwear               90
4               5   45    Male         Blouse     Clothing               49
...           ...  ...     ...            ...          ...              ...
3895         3896   40  Female         Hoodie     Clothing               28
3896         3897   52  Female       Backpack  Accessories               49
3897         3898   46  Female           Belt  Accessories               33
3898         3899   44  Female          Shoes     Footwear               77
3899         3900   52  Female        Handbag  Accessories               81

           location size      color  season  review_rating  \
0          Kentucky    L       Gray  Winter            3.1
1             Maine    L     Maroon  Winter            3.1
2     Massachusetts    S     Maroon  Spring            3.1
3      Rhode Island    M     Maroon  Spring            3.5
4            Oregon    M  Turquoise  Spring            2.7
...             ...  ...        ...     ...            ...
3895       Virginia    L  Turquoise  Summer            4.2
3896           Iowa    L      White  Spring            4.5
3897     New Jersey    L      Green  Spring            2.9
3898      Minnesota    S      Brown  Summer            3.8
3899     California    M      Beige  Spring            3.1

     subscription_status   shipping_type discount_applied  previous_purchases  \
0                    Yes         Express              Yes                  14
1                    Yes         Express              Yes                   2
2                    Yes   Free Shipping              Yes                  23
3                    Yes    Next Day Air              Yes                  49
4                    Yes   Free Shipping              Yes                  31
...                  ...             ...              ...                 ...
3895                  No  2-Day Shipping               No                  32
3896                  No    Store Pickup               No                  41
3897                  No        Standard               No                  24
3898                  No         Express               No                  24
3899                  No    Store Pickup               No                  33

     payment_method frequency_of_purchases    age_group  \
0             Venmo            Fortnightly  Middle-aged
1              Cash            Fortnightly  Young Adult
2       Credit Card                 Weekly  Middle-aged
3            PayPal                 Weekly  Young Adult
4            PayPal               Annually  Middle-aged
...             ...                    ...          ...
3895          Venmo                 Weekly        Adult
3896  Bank Transfer              Bi-Weekly  Middle-aged
3897          Venmo              Quarterly  Middle-aged
3898          Venmo                 Weekly        Adult
3899          Venmo              Quarterly  Middle-aged

      purchases frequency days
0                           14
1                           14
2                            7
3                            7
4                          365
...                        ...
3895                         7
3896                        14
3897                        90
3898                         7
3899                        90

[3900 rows x 19 columns]

In [28]:
pd.read_sql("SELECT TOP 5 * FROM customer;", engine)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchases frequency days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365